services:
  elimedia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elimedia
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_GOOGLE_PLACE_ID=${NEXT_PUBLIC_GOOGLE_PLACE_ID}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      
      # HTTP (Port 80) → Redirect auf HTTPS
      - "traefik.http.routers.elimedia-http.entrypoints=frontendsecure"
      - "traefik.http.routers.elimedia-http.rule=Host(`www.elimedia.de`)"
      - "traefik.http.routers.elimedia-http.middlewares=elimedia-https"

      - "traefik.http.middlewares.elimedia-https.redirectscheme.scheme=https"
      
      # Redirect elimedia.de → www.elimedia.de
      - "traefik.http.routers.elimedia-root.entrypoints=frontendsecure"
      - "traefik.http.routers.elimedia-root.rule=Host(`elimedia.de`)"
      - "traefik.http.routers.elimedia-root.middlewares=elimedia-www-redirect"
      - "traefik.http.routers.elimedia-root.tls=true"

      - "traefik.http.middlewares.elimedia-www-redirect.redirectregex.regex=^https?://elimedia\\.de(.*)"
      - "traefik.http.middlewares.elimedia-www-redirect.redirectregex.replacement=https://www.elimedia.de$1"
      - "traefik.http.middlewares.elimedia-www-redirect.redirectregex.permanent=true"
      
      # HTTPS Router
      - "traefik.http.routers.elimedia.entrypoints=frontendsecure"
      - "traefik.http.routers.elimedia.rule=Host(`www.elimedia.de`)"
      - "traefik.http.routers.elimedia.tls=true"
      - "traefik.http.routers.elimedia.tls.certresolver=leresolver"

networks:
  traefik-net:
    external: true