services:
  elimidia:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elimidia
    ports:
      - "3008:3008"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}
      - NEXT_PUBLIC_GOOGLE_MAPS_API_KEY=${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
      - NEXT_PUBLIC_GOOGLE_PLACE_ID=${NEXT_PUBLIC_GOOGLE_PLACE_ID}
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      
      # HTTP (Port 80) → Redirect auf HTTPS
      - "traefik.http.routers.elimidia-http.entrypoints=frontendsecure"
      - "traefik.http.routers.elimidia-http.rule=Host(`www.elimidia.de`)"
      - "traefik.http.routers.elimidia-http.middlewares=elimidia-https"

      - "traefik.http.middlewares.elimidia-https.redirectscheme.scheme=https"
      
      # Redirect elimidia.de → www.elimidia.de
      - "traefik.http.routers.elimidia-root.entrypoints=frontendsecure"
      - "traefik.http.routers.elimidia-root.rule=Host(`elimidia.de`)"
      - "traefik.http.routers.elimidia-root.middlewares=elimidia-www-redirect"
      - "traefik.http.routers.elimidia-root.tls=true"

      - "traefik.http.middlewares.elimidia-www-redirect.redirectregex.regex=^https?://elimidia\\.de(.*)"
      - "traefik.http.middlewares.elimidia-www-redirect.redirectregex.replacement=https://www.elimidia.de$1"
      - "traefik.http.middlewares.elimidia-www-redirect.redirectregex.permanent=true"
      
      # HTTPS Router
      - "traefik.http.routers.elimidia.entrypoints=frontendsecure"
      - "traefik.http.routers.elimidia.rule=Host(`www.elimidia.de`)"
      - "traefik.http.routers.elimidia.tls=true"
      - "traefik.http.routers.elimidia.tls.certresolver=leresolver"

networks:
  traefik-net:
    external: true